### ISSUE TITLE
code problem

### ISSUE THREAD

**Issue by Steven-jiaqi** [vandal-vpr/vg-transformers#13] opened 2023-03-14 09:33 UTC
I found this function  get_aggregator(args)  in tvg_net.py 82 lines. But  there is no args.aggregation '_'. And  i found the args.features_dim=768 in the function get_encoder(args). So I assign the args.features_dim =768.
But new error appeared:
             ValueError: optimizer got an empty parameter list

I can't solve this problem. I need your help.
I'm sorry to bother you again.
Looking forward to get your reply as soon as possible!

**Comment by ga1i13o** [comment] 2023-03-16 00:51
Hello, I think I solved your issue, and it is actually my fault.
The problem is at this line:

https://github.com/vandal-vpr/vg-transformers/blob/25537ed1689d4b5401113f6c4476fb8f0cf28158/tvg/models/tvg_net.py#L159

In the README I indicated that you should pass `--arch timesformer `, but the code actually expects you to pass 
`--arch Official-timesf`, as you can see in the line above. I will fix this as soon as I can and for now you can change your command line args to `--arch Official-timesf`

Thank you for noticing. I am closing your other issue

**Comment by Steven-jiaqi** [comment] 2023-03-16 02:36
Thank you for timely response.And I have another question. Is the --aggregation  'none' or  '_'?  It seems to be '_' in the code. 
Please forgive me for having a bit too many questions!  Best wishes to you!

**Comment by ga1i13o** [comment] 2023-03-17 11:00
Don't worry, I should have done a better job documenting the code.
Anyway for the TimeSformer you can pass either 'none' or leave the field empty, since in that case only the encoder will be called as you can see in the forward method (using timesformer sets  `fusion='early '` )

https://github.com/vandal-vpr/vg-transformers/blob/25537ed1689d4b5401113f6c4476fb8f0cf28158/tvg/models/tvg_net.py#L45-L49

**Comment by Steven-jiaqi** [comment] 2023-03-20 09:55
Thank you for your timely response.But when I run the  '--arch Official-timesf', the error happpened:
'Traceback (most recent call last):
  File "main_scripts/main_train.py", line 155, in <module>
    triplets_ds.compute_triplets(model)
  File "/home/user/yjq/vg-transformers/tvg/datasets/dataset.py", line 278, in compute_triplets
    self.compute_triplets_partial(model)
  File "/home/user/yjq/vg-transformers/tvg/datasets/dataset.py", line 337, in compute_triplets_partial
    cache = self.compute_cache(model, subset_ds, cache_shape=(len(self), self.features_dim))
  File "/home/user/yjq/vg-transformers/tvg/datasets/dataset.py", line 302, in compute_cache
    features = model(images.to(self.device))
  File "/home/user/.conda/envs/vgtransformers/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/user/.conda/envs/vgtransformers/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 165, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/user/.conda/envs/vgtransformers/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/user/yjq/vg-transformers/tvg/models/tvg_net.py", line 51, in forward
    x = self.encoder(x)
  File "/home/user/.conda/envs/vgtransformers/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/user/yjq/vg-transformers/TimeSformer/timesformer/models/vit.py", line 350, in forward
    x = self.model(x)
  File "/home/user/.conda/envs/vgtransformers/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/user/yjq/vg-transformers/TimeSformer/timesformer/models/vit.py", line 303, in forward
    x = self.forward_features(x)
  File "/home/user/yjq/vg-transformers/TimeSformer/timesformer/models/vit.py", line 251, in forward_features
    x, T, W = self.patch_embed(x)
  File "/home/user/.conda/envs/vgtransformers/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/user/yjq/vg-transformers/TimeSformer/timesformer/models/vit.py", line 170, in forward
    B, C, T, H, W = x.shape
ValueError: not enough values to unpack (expected 5, got 4)'
  I can't solve this problem, so I would like to seek your help.
  I am very sorry to bother you.

**Comment by Steven-jiaqi** [comment] 2023-03-21 09:50
I have solved the problem. I'm sorry to bother you.

**Comment by ga1i13o** [comment] 2023-03-21 10:29
Yes the issue should have been that you have to specify the image resolution. I am working to push a commit to make this automatic, and update the readme

**Closed as completed by ga1i13o** 2023-03-21 10:29 UTC
